apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: budget
  labels: { app: web }
spec:
  ports:
    - port: 3000
      targetPort: http
      name: http
  selector: { app: web }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: budget
spec:
  replicas: 1
  selector: { matchLabels: { app: web } }
  template:
    metadata: { labels: { app: web } }
    spec:
      containers:
        - name: rails
          image: devops-assessment-web:latest    
          imagePullPolicy: Never   # same tag you built inside Minikube
          ports: [ { containerPort: 3000, name: http } ]
          env:
            - name: RAILS_ENV
              value: production
            - name: SECRET_KEY_BASE         # add this
              value: dummy
            - name: DATABASE_URL
              value: postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@postgres:5432/$(POSTGRES_DB)
          envFrom: [ { secretRef: { name: postgres-secret } } ]
          readinessProbe:
            tcpSocket: { port: http }
            initialDelaySeconds: 10
          livenessProbe:
            tcpSocket: { port: http }
            initialDelaySeconds: 30
          resources:
            requests: { cpu: 100m, memory: 256Mi }
            limits:   { cpu: 500m, memory: 512Mi }
