default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: myuser
  password: mypass
  database: mydb
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: mydb_test

production:
  <<: *default
